In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('Titanic.csv')

In [3]:
df.sample(10)
# df.shape

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
82,82,1,3,female,NaN,0,0,7.7875,Q,Third,woman,False,NaN,Queenstown,yes,True
189,189,0,3,male,36.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
251,251,0,3,female,29.0,1,1,10.4625,S,Third,woman,False,G,Southampton,no,False
697,697,1,3,female,NaN,0,0,7.7333,Q,Third,woman,False,NaN,Queenstown,yes,True
371,371,0,3,male,18.0,1,0,6.4958,S,Third,man,True,NaN,Southampton,no,False
230,230,1,1,female,35.0,1,0,83.4750,S,First,woman,False,C,Southampton,yes,False
182,182,0,3,male,9.0,4,2,31.3875,S,Third,child,False,NaN,Southampton,no,False
857,857,1,1,male,51.0,0,0,26.5500,S,First,man,True,E,Southampton,yes,True
818,818,0,3,male,43.0,0,0,6.4500,S,Third,man,True,NaN,Southampton,no,True
256,256,1,1,female,NaN,0,0,79.2000,C,First,woman,False,NaN,Cherbourg,yes,True

In [4]:
df.isnull().mean()*100
df=df.drop(columns=['deck'])
df=df.dropna()
# df.info()
df=df.drop(columns=['who','adult_male','embark_town','alive','alone'])
df=df.drop(columns=['Unnamed: 0'])

In [5]:
df.sample(10)

     survived  pclass     sex   age  sibsp  parch      fare embarked   class
624         0       3    male  21.0      0      0   16.1000        S   Third
461         0       3    male  34.0      0      0    8.0500        S   Third
291         1       1  female  19.0      1      0   91.0792        C   First
160         0       3    male  44.0      0      1   16.1000        S   Third
817         0       2    male  31.0      1      1   37.0042        C  Second
737         1       1    male  35.0      0      0  512.3292        C   First
167         0       3  female  45.0      1      4   27.9000        S   Third
649         1       3  female  23.0      0      0    7.5500        S   Third
251         0       3  female  29.0      1      1   10.4625        S   Third
875         1       3  female  15.0      0      0    7.2250        C   Third

In [6]:
num_cols=['pclass','age','sibsp','parch','fare']
order_cols=['class']
cat_cols=['sex','embarked']

x=df.drop(columns=['survived'])
y=df['survived']

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
encoder=OrdinalEncoder(categories=[['Third', 'Second', 'First']])
df[order_cols]=encoder.fit_transform(df[order_cols]).astype(int)

In [9]:
df

     survived  pclass     sex   age  sibsp  parch     fare embarked  class
0           0       3    male  22.0      1      0   7.2500        S      0
1           1       1  female  38.0      1      0  71.2833        C      2
2           1       3  female  26.0      0      0   7.9250        S      0
3           1       1  female  35.0      1      0  53.1000        S      2
4           0       3    male  35.0      0      0   8.0500        S      0
..        ...     ...     ...   ...    ...    ...      ...      ...    ...
885         0       3  female  39.0      0      5  29.1250        Q      0
886         0       2    male  27.0      0      0  13.0000        S      1
887         1       1  female  19.0      0      0  30.0000        S      2
889         1       1    male  26.0      0      0  30.0000        C      2
890         0       3    male  32.0      0      0   7.7500        Q      0

[712 rows x 9 columns]

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
one=OneHotEncoder(sparse_output=False,drop='first',dtype='int')

In [12]:
df_encoded=pd.DataFrame(one.fit_transform(df[cat_cols]),columns=one.get_feature_names_out(cat_cols), index=df.index)

In [13]:
df_encoded

     sex_male  embarked_Q  embarked_S
0           1           0           1
1           0           0           0
2           0           0           1
3           0           0           1
4           1           0           1
..        ...         ...         ...
885         0           1           0
886         1           0           1
887         0           0           1
889         1           0           0
890         1           1           0

[712 rows x 3 columns]

In [14]:
df=df.drop(columns=['sex','embarked'])
df

     survived  pclass   age  sibsp  parch     fare  class
0           0       3  22.0      1      0   7.2500      0
1           1       1  38.0      1      0  71.2833      2
2           1       3  26.0      0      0   7.9250      0
3           1       1  35.0      1      0  53.1000      2
4           0       3  35.0      0      0   8.0500      0
..        ...     ...   ...    ...    ...      ...    ...
885         0       3  39.0      0      5  29.1250      0
886         0       2  27.0      0      0  13.0000      1
887         1       1  19.0      0      0  30.0000      2
889         1       1  26.0      0      0  30.0000      2
890         0       3  32.0      0      0   7.7500      0

[712 rows x 7 columns]

In [15]:
df=pd.concat([df,df_encoded],axis=1)

In [16]:
df

,survived,pclass,age,sibsp,parch,fare,class,sex_male,embarked_Q,embarked_S
0,0,3,22.0,1,0,7.2500,0,1,0,1
1,1,1,38.0,1,0,71.2833,2,0,0,0
2,1,3,26.0,0,0,7.9250,0,0,0,1
3,1,1,35.0,1,0,53.1000,2,0,0,1
4,0,3,35.0,0,0,8.0500,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...
885,0,3,39.0,0,5,29.1250,0,0,1,0
886,0,2,27.0,0,0,13.0000,1,1,0,1
887,1,1,19.0,0,0,30.0000,2,0,0,1
889,1,1,26.0,0,0,30.0000,2,1,0,0
890,0,3,32.0,0,0,7.7500,0,1,1,0

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
scalar=StandardScaler()

In [19]:
df3=scalar.fit_transform(df)
df= pd.DataFrame(df3, columns=df.columns, index=df.index)
df

,survived,pclass,age,sibsp,parch,fare,class,sex_male,embarked_Q,embarked_S
0,-0.824163,0.908600,-0.527669,0.522511,-0.506787,-0.516380,-0.908600,0.756138,-0.202326,0.534040
1,1.213352,-1.482983,0.577094,0.522511,-0.506787,0.694046,1.482983,-1.322511,-0.202326,-1.872519
2,1.213352,0.908600,-0.251478,-0.552714,-0.506787,-0.503620,-0.908600,-1.322511,-0.202326,0.534040
3,1.213352,-1.482983,0.369951,0.522511,-0.506787,0.350326,1.482983,-1.322511,-0.202326,0.534040
4,-0.824163,0.908600,0.369951,-0.552714,-0.506787,-0.501257,-0.908600,0.756138,-0.202326,0.534040
...,...,...,...,...,...,...,...,...,...,...
885,-0.824163,0.908600,0.646142,-0.552714,5.350885,-0.102875,-0.908600,-1.322511,4.942527,-1.872519
886,-0.824163,-0.287191,-0.182430,-0.552714,-0.506787,-0.407687,0.287191,0.756138,-0.202326,0.534040
887,1.213352,-1.482983,-0.734812,-0.552714,-0.506787,-0.086335,1.482983,-1.322511,-0.202326,0.534040
889,1.213352,-1.482983,-0.251478,-0.552714,-0.506787,-0.086335,1.482983,0.756138,-0.202326,-1.872519
890,-0.824163,0.908600,0.162808,-0.552714,-0.506787,-0.506928,-0.908600,0.756138,4.942527,-1.872519

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test=train_test_split(df,y,test_size=0.3,random_state=42)

In [22]:
x_train
x_test
y_train
y_test

641    1
496    1
262    0
311    1
551    0
      ..
818    0
478    0
325    1
175    0
37     0
Name: survived, Length: 214, dtype: int64

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
model=LogisticRegression()

In [32]:
model.fit(x_train,y_train)

LogisticRegression()

In [33]:
pred=model.predict(x_test)
# pred

In [34]:
from sklearn.metrics import accuracy_score
y_train

58     1
57     0
96     0
210    0
569    1
      ..
93     0
135    0
338    1
549    1
131    0
Name: survived, Length: 498, dtype: int64

In [36]:
acc=accuracy_score(y_test,pred)
acc

1.0

# Bhai bhari mistake ho chuki hai

## Hamne encoding aur scaling sab kuch bina dataset split kiye hi kar diya

## Jisse kya hua hai ki data leakage ho gaya hai

In [44]:
df=pd.read_csv('Titanic.csv')

In [45]:
df=df.drop(columns=['Unnamed: 0','who','adult_male','deck','embark_town','alive','alone'])

In [49]:
# df.info()
df=df.dropna()
# df.info()

In [50]:
x,y=df.drop(columns=['survived']),df['survived']

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [56]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [58]:
x.columns

Index(['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class'], dtype='object')

In [76]:
num=['pclass','age','sibsp','parch','fare']
ord_col=['class']
cat=['sex']

In [83]:
one=OneHotEncoder(sparse_output=False,drop='first',dtype='int')
od=OrdinalEncoder(categories=[['Third','Second','First']])
scalar=StandardScaler()

In [68]:
encoded1_x_train=pd.DataFrame(one.fit_transform(x_train[cat]),columns=one.get_feature_names_out(cat), index=x_train.index)

In [70]:
encoded1_x_test=pd.DataFrame(one.transform(x_test[cat]),columns=one.get_feature_names_out(cat), index=x_test.index)

In [80]:
encoded2_x_train=pd.DataFrame(od.fit_transform(x_train[ord_col]),columns=ord_col,index=x_train.index).astype(int)

In [82]:
encoded2_x_test=pd.DataFrame(od.transform(x_test[ord_col]),columns=ord_col,index=x_test.index).astype(int)

In [84]:
encoded3_x_train=pd.DataFrame(scalar.fit_transform(x_train[num]),columns=num,index=x_train.index).astype(int)

In [86]:
encoded3_x_test=pd.DataFrame(scalar.transform(x_test[num]),columns=num,index=x_test.index).astype(int)

## BEakr hi itne df banaye ordinal aur numeric to same me hi kar deta gadhe

In [87]:
x_train=x_train.drop(columns=x_train.columns)

In [89]:
x_train=pd.concat([x_train,encoded1_x_train,encoded2_x_train,encoded3_x_train],axis=1)

In [90]:
x_train

     sex_male  class  pclass  age  sibsp  parch  fare
54          1      2      -1    2      0      0     0
74          1      0       0    0      0      0     0
439         1      1       0    0      0      0     0
822         1      2      -1    0      0      0     0
373         1      2      -1    0      0      0     1
..        ...    ...     ...  ...    ...    ...   ...
515         1      2      -1    1      0      0     0
311         0      2      -1    0      1      1     3
609         0      2      -1    0      0      0     2
595         1      0       0    0      0      0     0
206         1      0       0    0      0      0     0

[534 rows x 7 columns]

In [91]:
x_test=x_test.drop(columns=x_test.columns)

In [92]:
x_test=pd.concat([x_test,encoded1_x_test,encoded2_x_test,encoded3_x_test],axis=1)

In [93]:
model=LogisticRegression()

In [94]:
model.fit(x_train,y_train)

LogisticRegression()

In [95]:
pred=model.predict(x_test)

In [96]:
acc=accuracy_score(y_test,pred)
acc

0.7808988764044944