In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('cars.csv')

In [4]:
df.shape

(8128, 5)

In [5]:
df.sample(10)

           brand  km_driven    fuel         owner  selling_price
5372     Hyundai      15000  Petrol   First Owner         750000
3542  Mitsubishi      39000  Diesel   First Owner        1700000
4162       Honda     160000  Diesel   First Owner         600000
2912       Honda      43000  Petrol   First Owner         700000
7656      Maruti      25000  Petrol   First Owner         316000
1417     Hyundai     120000  Diesel   First Owner         395000
1251      Maruti     210000  Diesel   First Owner         280000
7013        Tata     158000  Diesel   First Owner         202999
682       Toyota     160000  Diesel   First Owner        1225000
3376   Chevrolet      60000  Diesel  Second Owner         200000

In [6]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [7]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [9]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['selling_price']),df['selling_price'],test_size=0.3,random_state=42)

In [25]:
cols=['fuel','owner']

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [27]:
ohe=OneHotEncoder(sparse_output=False,drop='first',dtype='int')

In [29]:
encoded=ohe.fit_transform(x_train[cols])

In [31]:
encoded_df = pd.DataFrame(
    encoded,
    columns=ohe.get_feature_names_out(cols),
    index=x_train.index
)

In [32]:
encoded_df

,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
6783,0,0,1,0,0,0,1
1073,1,0,0,0,0,0,0
7756,1,0,0,0,0,0,0
144,0,0,1,0,0,0,0
6424,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...
5226,1,0,0,0,0,0,0
5390,1,0,0,0,1,0,0
860,0,0,1,0,0,0,0
7603,1,0,0,0,0,0,0
7270,0,0,1,0,1,0,0

In [33]:
x_train = x_train.drop(columns=cols)
x_train = pd.concat([x_train, encoded_df], axis=1)

In [34]:
x_train

,brand,km_driven,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
6783,Maruti,120000,0,0,1,0,0,0,1
1073,Toyota,100000,1,0,0,0,0,0,0
7756,BMW,39000,1,0,0,0,0,0,0
144,Toyota,39000,0,0,1,0,0,0,0
6424,Maruti,70000,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...
5226,Mahindra,120000,1,0,0,0,0,0,0
5390,Maruti,80000,1,0,0,0,1,0,0
860,Hyundai,35000,0,0,1,0,0,0,0
7603,Maruti,27000,1,0,0,0,0,0,0
7270,Maruti,70000,0,0,1,0,1,0,0